name: Run DDS Router subpackage tests in windows
description: Run DDS Router tests in windows for a specific package
inputs:
  package_name:
    description: 'Specifies the package build name to run the tests'
    required: true
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
  repetitions:
    description: 'Repeat until fail N times'
    required: true
    default: 1
  filter:
    description: 'Filter per test name'
    required: true
    default: "."
runs:
  using: composite
  steps:
  - run: >
      Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\' -Name DumpType -Value '2';
      Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\' -Name DumpFolder -Value '%LOCALAPPDATA%\CrashDumps';
      ctest -C ${{ inputs.cmake_build_type }} --test-dir build\${{ inputs.package_name }} -V --timeout 60 --label-exclude xfail --repeat-until-fail ${{ inputs.repetitions }} -R ${{ inputs.filter }}
    shell: pwsh
